#!/bin/sh

# Appearance
riverctl background-color 0x16161eff
riverctl border-width 1
riverctl border-color-focused 0x292e42ff
riverctl border-color-unfocused 0x16161eff
riverctl xcursor-theme capitaine-cursors 24

# Layout
riverctl attach-mode bottom                                # New view attached to the bottom of view stack
"${XDG_CONFIG_HOME:-$HOME/.config}/river/layout/stacktile" # Spawn layout generator

# Autostart
ENV="PATH WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE"
riverctl spawn "systemctl --user import-environment $ENV"
riverctl spawn "dbus-update-activation-environment --systemd $ENV"
riverctl spawn /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
riverctl spawn "wlr-randr --output VGA-2 --off"
riverctl spawn mako
riverctl spawn yambar
riverctl spawn "wlsunset -l -5.1 -L 119.4" # Makassar

## GTK
riverctl spawn "gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'"
riverctl spawn "gsettings set org.gnome.desktop.interface gtk-theme Adwaita"
riverctl spawn "gsettings set org.gnome.desktop.interface icon-theme Reversal-black-dark"
riverctl spawn "gsettings set org.gnome.desktop.interface cursor-theme capitaine-cursors"
riverctl spawn "gsettings set org.gnome.desktop.interface cursor-size 24"
riverctl spawn "gsettings set org.gnome.desktop.interface font-name 'SF Pro Display, Medium 10'"

# Input
riverctl hide-cursor timeout 2500 # Hide the cursor if it wasn't moved in the last n milliseconds
riverctl set-cursor-warp on-focus-change
riverctl set-repeat 50 250                                        # Set keyboard repeat rate (rate/second, delay(ms))
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad tap enabled # Enable touchpad tap-to-click

# Filter
## Make certain views start floating
riverctl rule-add float -app-id discord
riverctl rule-add float -app-id "firefox*" -title "Firefox — Sharing Indicator"
riverctl rule-add float -app-id "firefox*" -title "Library"
riverctl rule-add float -app-id "firefox*" -title "Picture-in-Picture"
riverctl rule-add float -app-id float-term
riverctl rule-add float -app-id imv
riverctl rule-add float -app-id jetbrains-studio
riverctl rule-add float -app-id mpv
riverctl rule-add float -app-id org.telegram.desktop
riverctl rule-add float -app-id thunar
riverctl rule-add float -app-id "Tor Bowser"
riverctl rule-add float -app-id wev
riverctl rule-add ssd -app-id "Tor Bowser"

# Mapping
## Mouse
riverctl map-pointer normal Super BTN_LEFT move-view    # Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_RIGHT resize-view # Super + Right Mouse Button to resize views

## Key
riverctl map normal Super+Shift E exit             # Super+Shift+E to exit river
riverctl map normal Super+Shift C close            # Super+Shift+C to close the focused view
riverctl map normal Super Return zoom              # Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Space toggle-float # Super+Space to toggle float
riverctl map normal Super F toggle-fullscreen      # Super+F to toggle fullscreen

### View management
#### Super+{J,K} to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

#### Super+Shift+{J,K} to swap the focused view with the next/previous view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

#### Super+Alt+{H,J,K,L} to move views
STEP=1
riverctl map -repeat normal Super+Alt H move left "$STEP"
riverctl map -repeat normal Super+Alt J move down "$STEP"
riverctl map -repeat normal Super+Alt K move up "$STEP"
riverctl map -repeat normal Super+Alt L move right "$STEP"

#### Super+Alt+Shift+{H,J,K,L} to resize views
DELTA=2
riverctl map -repeat normal Super+Alt+Shift H resize horizontal -"$DELTA"
riverctl map -repeat normal Super+Alt+Shift J resize vertical -"$DELTA"
riverctl map -repeat normal Super+Alt+Shift K resize vertical "$DELTA"
riverctl map -repeat normal Super+Alt+Shift L resize horizontal "$DELTA"

#### Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

### Output management
#### Super+{Period,Comma} to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

#### Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

### Tag management
USED_TAGS=9

for i in $(seq 1 "$USED_TAGS"); do
	tag=$((1 << (i - 1)))
	riverctl map normal Super "$i" set-focused-tags $tag               # Super+[1-9] to focus tag [0-8]
	riverctl map normal Super+Shift "$i" set-view-tags $tag            # Super+Shift+[1-9] to tag focused view with tag [0-8]
	riverctl map normal Super+Control "$i" toggle-focused-tags $tag    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
	riverctl map normal Super+Shift+Control "$i" toggle-view-tags $tag # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
done

ALL_TAGS=$(((1 << USED_TAGS) - 1))
riverctl map normal Super 0 set-focused-tags $ALL_TAGS    # Super+0 to focus all tags
riverctl map normal Super+Shift 0 set-view-tags $ALL_TAGS # Super+Shift+0 to tag focused view with all tags
riverctl map normal Super Tab focus-previous-tags
riverctl map normal Super+Shift Tab send-to-previous-tags

SCRATCH_TAG=$((1 << (USED_TAGS + 1)))
riverctl map normal Super P toggle-focused-tags $SCRATCH_TAG
riverctl map normal Super+Shift P set-view-tags $SCRATCH_TAG
riverctl spawn-tagmask $((ALL_TAGS ^ SCRATCH_TAG))

### Media key
for mode in normal locked; do
	riverctl map $mode None XF86AudioRaiseVolume spawn "volctl raise"
	riverctl map $mode None XF86AudioLowerVolume spawn "volctl lower"
	riverctl map $mode None XF86AudioMute spawn "volctl mute"

	riverctl map $mode None XF86MonBrightnessUp spawn "light r"
	riverctl map $mode None XF86MonBrightnessDown spawn "light l"
done

### App
APP_LAUNCHER=fuzzel
TERMINAL=alacritty
ALT_TERMINAL=foot
WEB_BROWSER=firefox-developer-edition
TERM_FILE_MANAGER="$TERMINAL --class float-term -e lf"
FILE_MANAGER=thunar
SESSION_LOCKER="waylock -fork-on-lock -init-color 0x16161E -input-color 0x1A1B26 -fail-color 0xF7768E"

riverctl map normal Alt Space spawn "$APP_LAUNCHER"
riverctl map normal Super Space spawn "$TERMINAL"
riverctl map normal Super+Shift Return spawn "$ALT_TERMINAL"
riverctl map normal Alt Return spawn "$TERMINAL --class float-term"
riverctl map normal Alt BackSpace spawn "$TERMINAL -e tmux new -As scratch"
riverctl map normal Alt Delete spawn "$SESSION_LOCKER"
riverctl map normal Control+Alt Delete spawn "fuzzel-power-prompt"
riverctl map normal None Print spawn "grot f"
riverctl map normal Super Print spawn "grot r"

riverctl declare-mode launcher
riverctl map normal Super R enter-mode launcher
riverctl map launcher None F spawn "$WEB_BROWSER"
riverctl map launcher Shift F spawn "$WEB_BROWSER --private-window"
riverctl map launcher None E spawn "$TERM_FILE_MANAGER"
riverctl map launcher Shift E spawn "$FILE_MANAGER"
riverctl map launcher None Escape enter-mode normal
riverctl map launcher None C enter-mode normal
riverctl map launcher Control bracketleft enter-mode normal
