#!/bin/sh

export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=river
export XDG_CURRENT_DESKTOP=river

export GDK_BACKEND=wayland
export GTK_THEME=Adwaita:dark
export XCURSOR_THEME=capitaine-cursors
export XCURSOR_SIZE=24

export QT_QPA_PLATFORM="wayland;xcb"
export QT_QPA_PLATFORMTHEME=qt5ct

export MOZ_ENABLE_WAYLAND=1
export MOZ_GTK_TITLEBAR_DECORATION=client

export AWT_TOOLKIT=MToolkit
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

export LIGHT_DAY_TIME=8
export LIGHT_DAY_BRIGHTNESS=60
export LIGHT_NIGHT_TIME=18
export LIGHT_NIGHT_BRIGHTNESS=40

export PYTHON_TYPE_STUBS="$HOME/git/python-type-stubs/"

export SESSION_LOCKER="waylock -fork-on-lock -init-color 0x16161E -input-color 0x1A1B26 -fail-color 0xF7768E"
export SESSION_EXIT_CMD="riverctl exit"

export RIVER_CONF_D="${XDG_CONFIG_HOME:-$HOME/.config}/river"
export RIVER_STATE_D="${XDG_STATE_HOME:-$HOME/.local/state}/river"
[ ! -d "$RIVER_STATE_D" ] && mkdir -p "$RIVER_STATE_D"

loglv=warning
RIVER_LOG="$RIVER_STATE_D/$(date +%Y%m%d%H%M%S).$loglv.log"
export RIVER_LOG
exec dbus-run-session -- river -log-level "$loglv" >"$RIVER_LOG" 2>&1
