#!/bin/sh -e

export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=river
export XDG_CURRENT_DESKTOP=river

export GDK_BACKEND=wayland
export GTK_THEME=Adwaita:dark
export XCURSOR_THEME=capitaine-cursors
export XCURSOR_SIZE=24

export QT_QPA_PLATFORM="wayland;xcb"
export QT_QPA_PLATFORMTHEME=qt5ct

export MOZ_ENABLE_WAYLAND=1
export MOZ_GTK_TITLEBAR_DECORATION=client

export AWT_TOOLKIT=MToolkit
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

export PYTHON_TYPE_STUBS="$HOME/git/python-type-stubs/"

LOG=/tmp/river-"$(date +%F_%s)".log
exec river -log-level debug >"$LOG" 2>&1
