#!/bin/sh

LAYOUT="rivertile"

riverctl spawn "$LAYOUT -view-padding 0 -outer-padding 0"
riverctl default-layout "$LAYOUT"

riverctl map normal Super H send-layout-cmd "$LAYOUT" "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd "$LAYOUT" "main-ratio +0.05"

riverctl map normal Super+Shift H send-layout-cmd "$LAYOUT" "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd "$LAYOUT" "main-count -1"

riverctl map normal Super Up send-layout-cmd "$LAYOUT" "main-location top"
riverctl map normal Super Right send-layout-cmd "$LAYOUT" "main-location right"
riverctl map normal Super Down send-layout-cmd "$LAYOUT" "main-location bottom"
riverctl map normal Super Left send-layout-cmd "$LAYOUT" "main-location left"
