#!/bin/sh -e

LAYOUT="stacktile"
PADDING=0

riverctl spawn "$LAYOUT \
    --per-tag-config \
    --primary-sublayout full \
    --inner-padding $PADDING \
    --outer-padding $PADDING"
riverctl default-layout "$LAYOUT"

riverctl map -repeat normal Super H send-layout-cmd "$LAYOUT" "primary_ratio -0.01"
riverctl map -repeat normal Super L send-layout-cmd "$LAYOUT" "primary_ratio +0.01"

riverctl map normal Super M send-layout-cmd "$LAYOUT" "all_primary toggle"
riverctl map normal Super+Shift H send-layout-cmd "$LAYOUT" "primary_count +1"
riverctl map normal Super+Shift L send-layout-cmd "$LAYOUT" "primary_count -1"
riverctl map normal Alt+Shift K send-layout-cmd "$LAYOUT" "secondary_count +1"
riverctl map normal Alt+Shift J send-layout-cmd "$LAYOUT" "secondary_count -1"

riverctl map normal Super Up send-layout-cmd "$LAYOUT" "primary_position top"
riverctl map normal Super Right send-layout-cmd "$LAYOUT" "primary_position right"
riverctl map normal Super Down send-layout-cmd "$LAYOUT" "primary_position bottom"
riverctl map normal Super Left send-layout-cmd "$LAYOUT" "primary_position left"

riverctl map normal Super+Alt Space send-layout-cmd "$LAYOUT" "primary_sublayout full,columns,rows"
riverctl map normal Super+Shift+Alt Space send-layout-cmd "$LAYOUT" "secondary_sublayout rows,columns,stack,full"
riverctl map normal Super+Control+Alt Space send-layout-cmd "$LAYOUT" "remainder_sublayout stack,grid,full"

riverctl map normal Super+Alt Equal send-layout-cmd "$LAYOUT" "all_padding +1"
riverctl map normal Super+Alt Minus send-layout-cmd "$LAYOUT" "all_padding -1"
riverctl map normal Super+Alt 0 send-layout-cmd "$LAYOUT" "all_padding $PADDING"
riverctl map normal Alt+Shift 0 send-layout-cmd "$LAYOUT" "reset"
