[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[colors.normal]
red = "#f7768e"
green = "#9ece6a"
blue = "#7aa2f7"
cyan = "#449dab"
magenta = "#ad8ee6"
yellow = "#e0af68"
black = "#32344a"
white = "#787c99"

[colors.bright]
red = "#ff7a93"
green = "#b9f27c"
blue = "#7da6ff"
cyan = "#0db9d7"
magenta = "#bb9af7"
yellow = "#ff9e64"
black = "#444b6a"
white = "#acb0d0"
