[[keyboard.bindings]]
mods = "Shift"
key = "Return"
chars = "\u001B[13;2u"

[[keyboard.bindings]]
mods = "Control"
key = "Return"
chars = "\u001B[13;5u"

[[keyboard.bindings]]
mods = "Control|Shift"
key = "Return"
action = "SpawnNewInstance"

[[keyboard.bindings]]
mods = "Control|Shift"
key = "N"
action = "CreateNewWindow"

[[keyboard.bindings]]
mods = "Super"
key = "N"
action = "CreateNewWindow"

[[keyboard.bindings]]
mode = "Vi"
key = "Q"
action = "ToggleViMode"

[[keyboard.bindings]]
mode= "Vi"
mods = "Control"
key = "["
action = "ToggleViMode"

[[keyboard.bindings]]
mode = "Vi"
key = "d"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
mode = "Vi"
key = "u"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
mode = "Vi"
key = "Space"
action = "ScrollPageDown"

[[keyboard.bindings]]
mode = "Vi"
mods = "Shift"
key = "Space"
action = "ScrollPageUp"
