[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Super"

[[keyboard.bindings]]
mode = "Vi"
key = "Q"
action = "ToggleViMode"

[[keyboard.bindings]]
mode= "Vi"
mods = "Control"
key = "["
action = "ToggleViMode"

[[keyboard.bindings]]
mode = "Vi"
key = "d"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
mode = "Vi"
key = "u"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
mode = "Vi"
key = "Space"
action = "ScrollPageDown"

[[keyboard.bindings]]
mode = "Vi"
mods = "Shift"
key = "Space"
action = "ScrollPageUp"
