#!/usr/bin/env bash

REPO="${MAVEN_USER_HOME:-$HOME/.m2}/repository"
PACKAGE="com/google/googlejavaformat/google-java-format"
JAR="google-java-format-HEAD-SNAPSHOT-all-deps.jar"
exec java -jar "$REPO/$PACKAGE/HEAD-SNAPSHOT/$JAR" "$@"
