#!/usr/bin/env bash

main() {
    picom --config "$PICOM_CONF" &
    disown
    sleep 0.5s
    dunstify -t 2500 -i "compton" -a "picom" \
        -h string:x-dunst-stack-tag:picom \
        "Picom Restarted"
}

if (pgrep picom >/dev/null); then
    kill -KILL "$(pgrep picom)"
fi

main
