#!/usr/bin/env bash

run() {
    picom --config "$PICOM_CONF" &
    disown
    sleep 0.5s
    dunstify -t 2500 -i "compton" "Picom Restarted"
}

if (pgrep picom >/dev/null); then
    kill -KILL "$(pgrep picom)"
fi

run
