#!/usr/bin/env bash

help() (
    printf "scrgen - Generate Script with Shebang\n"
    printf "\nUsage: \e[1;32mscrgen \e[36m<shell> \e[34m[filename]\e[0m\n"
    printf "\nAvailabe \e[1;36mshell\e[0m:\n\n"
    printf "\e[1m"
    printf "    - bash\n"
    printf "    - sh\n"
    printf "    - node\n"
    printf "    - python\n"
    printf "\e[0m\n"
)

main() (

    [[ -z "$1" ]] && help && return 0
    [[ -z "$2" ]] && printf "Please specify \e[1;34mfilename\e[0m\n" && return 1

    local SHELL="sh"

    case "$1" in
        "bash") SHELL="bash" ;;
        "sh") SHELL="sh" ;;
        "node") SHELL="node" ;;
        "python") SHELL="python" ;;
        *) help && return 1 ;;
    esac

    echo "#!/usr/bin/env $SHELL" >"$2"
)

main "$@"
