#!/bin/sh -e

main() (
	LOCK="  Lock"
	SUSPEND="  Suspend"
	HIBERNATE="  Hibernate"
	POWER_OFF="  Poweroff"
	REBOOT="  Reboot"
	LOG_OUT="  Exit"
	OPTIONS="$LOCK\n$SUSPEND\n$HIBERNATE\n$POWER_OFF\n$REBOOT\n$LOG_OUT"

	IFS=. read -r uptime _ </proc/uptime
	DAY=$((uptime / 60 / 60 / 24))
	UPTIME=$(printf "%02d hours %02d minutes" $((uptime / 60 / 60 % 24)) $((uptime / 60 % 60)))
	[ "$DAY" -gt 0 ] && UPTIME="$DAY days $UPTIME"
	ACTION=$(printf '%b' "$OPTIONS" |
		fuzzel \
			--prompt "$UPTIME " \
			--no-icons \
			--lines 6 \
			--width 24 \
			--dmenu)
	case "$ACTION" in
		"$POWER_OFF")
			sleep 0.2s && $SYSTEM_SHUTDOWN_CMD
			;;
		"$REBOOT")
			sleep 0.2s && $SYSTEM_REBOOT_CMD
			;;
		"$SUSPEND")
			sleep 0.2s && $SYSTEM_SUSPEND_CMD
			;;
		"$HIBERNATE")
			sleep 0.2s && $SYSTEM_HIBERNATE_CMD
			;;
		"$LOCK")
			sleep 0.2s && $SESSION_LOCKER
			;;
		"$LOG_OUT")
			sleep 0.2s && $SESSION_EXIT_CMD
			;;
	esac
)

main "$@"
