#!/bin/sh -e

# grot: grim (+slurp) screenshot

usage() (
	printf "Usage: grot \e[1mscope\e[0m \e[3m[EXT]\e[0m

\e[1mscope\e[0m:
  - r|region
  - f|full
  - p|pick

\e[3m[EXT]\e[0m (optional, default: jpeg):
  - jpeg
  - png
  - ppm
"
)

notify() (
	if ! command -v notify-send >/dev/null; then
		exit
	fi

	SCOPE="$1"
	FILEPATH="$2"
	FILENAME="$3"

	[ -f "$FILEPATH/$FILENAME" ] && {
		notify-send "$SCOPE Screenshot" \
			"  ~${FILEPATH##"$HOME"}\n: $FILENAME" \
			-a grot \
			-t 3000 \
			-i "$FILEPATH/$FILENAME"
)

pick() (
	if ! command -v convert >/dev/null; then
		printf "aborted: convert command not found\n"
		exit
	fi

	grim -g "$(slurp -p)" -t ppm - | convert - -format '%[pixel:p{0,0}]' txt:-
)

main() (
	[ -z "$1" ] && usage && exit 0
	SCOPE="$1"

	EXT="${2:-jpeg}"
	case $EXT in
		png | jpeg | ppm) ;;
		*) EXT="jpeg" ;; # fallback to jpeg for wrong value
	esac

	FLAG="-t $EXT"
	if [ "$EXT" = "jpeg" ]; then
		FLAG="$FLAG -q 100"
	fi

	timestamp="$(date +'%Y%m%dT%H%M%S')"
	FILENAME="${timestamp}.$EXT"
	FILEPATH="${GRIM_DEFAULT_DIR:-${XDG_PICTURES_DIR:-$HOME/picture}}"
	[ ! -d "$FILEPATH" ] && mkdir -p "$FILEPATH"
	# Handle more than 1 shot per seconds
	i=1
	while [ -f "${FILEPATH}/$FILENAME" ]; do
		FILENAME="${timestamp}N$(printf "%03d" "$i").$EXT"
		i=$((i + 1))
	done
	DEST="${FILEPATH}/$FILENAME"

	case $SCOPE in
		"r" | "region")
			SCOPE="Region"
			grim $FLAG -g "$(slurp)" "$DEST"
			;;
		"f" | "full")
			SCOPE="Fullscreen"
			grim $FLAG "$DEST"
			;;
		"p" | "pick")
			pick
			exit
			;;
		"h" | "help")
			usage
			exit
			;;
		*)
			printf "\e[0;91m%s\e[0m " "$SCOPE"
			printf "is an invalid argument.\n"
			usage
			exit 1
			;;
	esac

	notify "$SCOPE" "$FILEPATH" "$FILENAME"
)

# Required dependencies
for DEP in grim slurp; do
	if ! command -v "$DEP" >/dev/null; then
		printf "Missing dependencies: %s\n" "$DEP"
		exit 1
	fi
done

# Optional dependencies
for DEP in convert notify-send; do
	if ! command -v "$DEP" >/dev/null; then
		printf "Missing optional dependencies: %s\n" "$DEP"
	fi
done

main "$@"
