#!/bin/sh -e

# grot: grim (+slurp) screenshot

usage() (
	printf "Usage: grot \e[3mscope\e[0m

\e[3mscope\e[0m:
  - r|region
  - f|full
  - p|pick
"
)

notify() (
	if ! command -v notify-send >/dev/null; then
		exit
	fi

	SCOPE="$1"
	PATH="$2"
	FILENAME="$3"

	# FIX: notify-send not found in here or if with `if` block
	[ -f "{$PATH}/$FILENAME" ] &&
		notify-send "$SCOPE Screenshot" "$FILENAME" \
			-t 2500 \
			-i "$PATH/$FILENAME"
)

shot() (
	grim -t jpeg -q 100 "$@"
)

region() (
	shot -g "$(slurp)" "$@"
)

full() (
	shot "$@"
)

pick() (
	if ! command -v convert >/dev/null; then
		printf "aborted: convert command not found\n"
		exit
	fi

	grim -g "$(slurp -p)" -t ppm - | convert - -format '%[pixel:p{0,0}]' txt:-
)

main() (
	[ -z "$1" ] && usage && exit 0

	SCOPE="$1"
	FN="$1"
	FILENAME="$(date +'%Y%m%d_%H%M%S').jpeg"
	SAVEPATH="${GRIM_DEFAULT_DIR:-$XDG_PICTURES_DIR:-$HOME/picture}"

	case $SCOPE in
		"r" | "region")
			SCOPE="Region"
			FN="region"
			;;
		"f" | "full")
			SCOPE="Fullscreen"
			FN="full"
			;;
		"p" | "pick")
			pick
			exit
			;;
		"h" | "help")
			usage
			exit
			;;
		*)
			printf "\e[0;91m%s\e[0m " "$SCOPE"
			printf "is an invalid argument.\n"
			usage
			exit 1
			;;
	esac

	"$FN" "$SAVEPATH/$FILENAME"
	if ! command -v notify-send >/dev/null; then
		exit
	fi

	notify-send "$SCOPE Screenshot" "$FILENAME" \
		-t 2500 \
		-i "$SAVEPATH/$FILENAME"
)

# Required dependencies
for DEP in grim slurp; do
	if ! command -v "$DEP" >/dev/null; then
		printf "Missing dependencies: %s\n" "$DEP"
		exit 1
	fi
done

# Optional dependencies
for DEP in convert notify-send; do
	if ! command -v "$DEP" >/dev/null; then
		printf "Missing optional dependencies: %s\n" "$DEP"
	fi
done

main "$@"
