#!/usr/bin/env bash

PLUGINS="$JDTLS_HOME"/plugins
CONFIG="$JDTLS_HOME"/config_linux

unset JAVA_TOOL_OPTIONS
GRADLE_HOME="$LOCAL_LIB"/gradle/bin/gradle exec "$JAVA_HOME"/bin/java \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -Dlog.protocol=true \
    -Dlog.level=ALL \
    -Xms1g \
    -Xmx2G \
    --add-modules=ALL-SYSTEM \
    --add-opens java.base/java.util=ALL-UNNAMED \
    --add-opens java.base/java.lang=ALL-UNNAMED \
    -jar "$PLUGINS"/org.eclipse.equinox.launcher_*.jar \
    -configuration "$CONFIG" \
    -data "${1:-$JAVA_WORKSPACE}"
