#!/usr/bin/env bash

main() (
    picom --config "$PICOM_CONF" &
    sleep 0.5s
    dunstify -t 2500 -i "compton" -a "picom" \
        -h string:x-dunst-stack-tag:picom \
        "Picom Restarted"
)

kill -KILL "$(pgrep picom)" &>/dev/null
main
