#!/bin/sh -e

prompt_power() {
    SELECTED="${1:-4}"
    ORIENTATION="${2:-"hor"}"
    POWER_OFF=""
    REBOOT=""
    SUSPEND=""
    HIBERNATE=""
    LOCK=""
    LOG_OUT=""
    OPTIONS="$POWER_OFF\n$REBOOT\n$SUSPEND\n$HIBERNATE\n$LOCK\n$LOG_OUT"
    ACTION
    ACTION=$(printf '%b' "$OPTIONS" |
        rofi -dmenu \
            -theme-str '@import "themes/tokyonight/power.'"$ORIENTATION"'"' \
            -selected-row "$SELECTED" -no-default-config)

    case "$ACTION" in
        "$POWER_OFF")
            sleep 0.2s && systemctl poweroff
            ;;
        "$REBOOT")
            sleep 0.2s && systemctl reboot
            ;;
        "$SUSPEND")
            sleep 0.2s && systemctl suspend
            ;;
        "$HIBERNATE")
            sleep 0.2s && systemctl hibernate
            ;;
        "$LOCK")
            sleep 0.2s && slock
            ;;
        "$LOG_OUT")
            sleep 0.2s && killall xinit
            ;;
    esac
}

prompt_power "$@"
