#!/bin/sh -e

main() (
	[ -z "$1" ] && help && exit

	ACTION="$1"
	shift
	case "$ACTION" in
		e | ed)
			ed "$@"
			;;
		ex | x)
			ex "$@"
			;;
		g | gen)
			gen "$@"
			;;
		ge | ged)
			gen "$@" && shift && ed "$@"
			;;
		*)
			help
			exit 1
			;;
	esac
)

help() (
	printf "scr - Local Script Manager

Usage: \e[1;32mscr \e[96m<action> \e[94m<action-arg>\e[0m \e[3m[DEST_DIR]\e[0m

Availabe \e[1;96maction\e[0m:
	- g|gen : Generate a script
	- e|ed  : Edit an existing script
	- ge|ged: Generate, then edit the script
	- x|ex  : Make a script executable

\e[1;96mg|gen\e[0m,\e[1;96mge|ged\e[0m action-arg: \e[1;94m<shebang>\e[0m \e[1m<filename>\e[0m
	Run without an argument to see the available \e[34mshebang\e[0m

\e[1;96me|ed\e[0m,\e[1;96mx|ex\e[0m action-arg: \e[1m<filename>\e[0m

\e[3mDEST_DIR\e[0m is optional, if not provided, fallback to
	- \$LOCAL_SCRIPT
	- \$HOME/.local/script
"
)

gen() (
	if [ -z "$1" ]; then
		printf "Usage: \e[1;32mscr \e[96m<g|gen> \e[94m<shebang>\e[0m \e[1m<filename>\e[0m \e[3m[DEST_DIR]\e[0m

Available \e[34mshebang\e[0m
	- sh
	- bash
	- node
	- python
"
		exit
	fi

	SHELL="sh"
	case "$1" in
		"bash") SHELL="bash" ;;
		"sh") SHELL="sh" ;;
		"node") SHELL="node" ;;
		"python") SHELL="python" ;;
		*)
			printf "\e[1;91m%s\e[0m shebang is not available\n" "$1"
			gen
			exit 1
			;;
	esac

	[ -z "$2" ] && printf "Please specify \e[1;34mfilename\e[0m\n" && exit 1

	DEST_DIR="${LOCAL_SCRIPT:-$HOME/.local/script}"
	[ -n "$3" ] && DEST_DIR="$3"
	[ ! -d "$DEST_DIR" ] && mkdir -p "$DEST_DIR"

	if [ -f "$DEST_DIR/$2" ]; then
		printf "\e[0;92;40m %s \e[0m already exist\n" "$DEST_DIR/$2"
		exit
	fi

	case "$SHELL" in
		"sh")
			echo "#!/bin/sh -e" >"$DEST_DIR/$2"
			;;
		*)
			echo "#!/usr/bin/env $SHELL" >"$DEST_DIR/$2"
			;;
	esac
)

ed() (
	CWD="$PWD"

	DEST_DIR="${LOCAL_SCRIPT:-$HOME/.local/script}"
	[ -n "$2" ] && DEST_DIR="$2"
	[ ! -d "$DEST_DIR" ] && mkdir -p "$DEST_DIR"

	if [ "$1" = "" ]; then
		cd "$DEST_DIR"
		"$EDITOR"
		cd "$CWD"
		exit
	fi

	if [ ! -f "$DEST_DIR/$1" ]; then
		printf "\e[0;91;40m %s \e[0m No such file in %s\n" "$1" "$DEST_DIR"
		exit 1
	fi

	cd "$DEST_DIR"
	"$EDITOR" "$1"
	cd "$CWD"
)

ex() (
	DEST_DIR="${LOCAL_SCRIPT:-$HOME/.local/script}"
	[ -n "$2" ] && DEST_DIR="$2"
	[ ! -d "$DEST_DIR" ] && mkdir -p "$DEST_DIR"

	if [ ! -f "$DEST_DIR/$1" ]; then
		printf "\e[0;91;40m %s \e[0m No such file in %s\n" "$1" "$DEST_DIR"
		exit 1
	fi

	if [ -x "$DEST_DIR/$1" ]; then
		printf "%s/%s already executable\n" "$DEST_DIR" "$1"
		exit
	fi

	if ! chmod 744 "$DEST_DIR/$1"; then
		printf "Can not make %s/%s executable\n" "$DEST_DIR" "$1"
		exit 1
	fi

	printf "%s/%s is now executable\n" "$DEST_DIR" "$1"
)

main "$@"
