#!/usr/bin/env bash

volctl() {
    local PERCENTAGE IS_MUTED SINKS
    mapfile -t SINKS < <(pactl list sinks short | cut -f 1)

    case "$1" in
        "raise")
            PERCENTAGE=$(
                pacmd list-sinks |
                    grep -A 15 '* index' |
                    awk '/volume: /{ print $5 }' |
                    grep -m 1 % |
                    sed 's/[%|,]//g'
            )
            if [[ "$PERCENTAGE" -lt 100 ]]; then
                for sink in "${SINKS[@]}"; do
                    pactl set-sink-mute "$sink" false
                    pactl set-sink-volume "$sink" +5%
                done
                # pactl set-sink-mute "${SINKS[-1]}" false
                # pactl set-sink-volume "${SINKS[-1]}" +5%
            fi
            ;;
        "lower")
            for sink in "${SINKS[@]}"; do
                pactl set-sink-mute "$sink" false
                pactl set-sink-volume "$sink" -5%
            done
            ;;
        "mute")
            for sink in "${SINKS[@]}"; do
                pactl set-sink-mute "$sink" toggle
            done
            ;;
    esac

    PERCENTAGE=$(
        pacmd list-sinks |
            grep -A 15 '* index' |
            awk '/volume: /{ print $5 }' |
            grep -m 1 % |
            sed 's/[%|,]//g'
    )

    IS_MUTED=$(
        pacmd list-sinks |
            grep -A 15 '* index' |
            awk '/muted:/{ print $2 }'
    )

    local ICON="墳"
    local COLOR="#0db9d7"

    if [[ "$IS_MUTED" == "yes" || "$PERCENTAGE" == 0 ]]; then
        ICON="婢"
        COLOR="#444b6a"
    else
        if [[ "$PERCENTAGE" -ge 70 ]]; then
            COLOR="#ff7a93"
        elif [[ "$PERCENTAGE" -le 30 ]]; then
            COLOR="#a9b1d6"
        fi
    fi

    local FG="string:fgcolor:$COLOR"
    local FR="string:frcolor:$COLOR"
    local HL="string:hlcolor:$COLOR"
    PERCENTAGE=$(printf "%3d" "$PERCENTAGE")

    dunstify -a "Audio Volume" -t 3000 \
        -h string:x-dunst-stack-tag:volctl \
        -h "$FG" -h "$FR" -h "$HL" \
        -h int:value:"$PERCENTAGE" \
        "$ICON" "${PERCENTAGE}"
}

volctl "$@"
