#!/bin/bash

# Set decoration geometry
berryc border_width 1
berryc inner_border_width 1
berryc title_height 0
berryc top_gap 30
berryc edge_gap 8 8 8 8
berryc decorate_new "false"

# Set decoration colors
berryc focus_color 444b6a
berryc unfocus_color 32344a
berryc inner_focus_color 444b6a
berryc inner_unfocus_color 32344a
berryc text_focus_color a9b1d6
berryc text_unfocus_color 787c99

# Other options
berryc smart_place "true"
berryc draw_text "false"
berryc edge_lock "true"
berryc set_font "SF Mono-9"
berryc focus_follows_pointer "true"
