#!/usr/bin/env bash
CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"
DISPLAY=":0"
SXHKD_CONF="$CONF_DIR/sxhkd"
BERRY_SXHKD="$SXHKD_CONF/wm/berry.sxhkdrc"
DUNST_SXHKD="$SXHKD_CONF/util/dunst.sxhkdrc"
COMMON_SXHKD="$SXHKD_CONF/common.sxhkdrc"
BERRYC="$CONF_DIR/berry/command/"
STARTXD="$CONF_DIR/berry/startx.d/"

export BERRYC

for SCRIPT in "$STARTXD"*.sh; do
    # shellcheck source=/dev/null
    [[ -x "$SCRIPT" ]] && . "$SCRIPT"
done

exec dunst &
exec sxhkd -c "$BERRY_SXHKD" "$DUNST_SXHKD" "$COMMON_SXHKD" &
exec picom --config "$CONF_DIR/picom/berry.picom.conf" &
exec unclutter --timeout 3 \
    --ignore-scrolling \
    --hide-on-touch \
    --start-hidden &

exec berry
